# Generated by Django 5.2.6 on 2025-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('carno', models.IntegerField(primary_key=True, serialize=False)),
                ('carname', models.CharField(max_length=100)),
                ('carowner', models.CharField(max_length=100)),
                ('carowner_phoneno', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
