# Generated by Django 5.2.6 on 2025-09-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='price',
            new_name='price_in_rupees',
        ),
    ]
